#! /usr/bin/env bash
leftwm command "UnloadTheme"

leftwm command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"

if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$HOME/.config/leftwm/themes/current/wallpaper.jpg"
fi
